participants:
  - el_type: geth
    cl_type: lighthouse
    cl_extra_params: 
      - --always-prepare-payload

network_params:
  seconds_per_slot: 12
  gloas_fork_epoch: 1000

mev_type: buildoor

additional_services:
  - dora
  - spamoor
